[Rahul] | 122 | Add. Commons Build Steps

diff --git a/.github/workflows/build_upload.yml b/.github/workflows/build_upload.yml
--- a/.github/workflows/build_upload.yml
+++ b/.github/workflows/build_upload.yml
@@ -16,6 +16,10 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
+        with:
+          repository: Bahmni-HWC/openmrs-module-openhmis.commons
+          path: openmrs-module-openhmis.commons
+      - uses: actions/checkout@v2
       - name: Set up JDK 1.8
         uses: actions/setup-java@v1
         with:
@@ -27,32 +31,32 @@ jobs:
           key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
           restore-keys: ${{ runner.os }}-m2-
       - name: Build with Maven
-        run: mvn clean install -DskipTests=true
+        run: |
+          cd openmrs-module-openhmis.commons
+          mvn clean install -DskipTests=true
       - run: mkdir output && cp omod/target/*.omod output
       - uses: actions/upload-artifact@v2
         with:
           name: omod-artifacts
           path: output
-      - name: Build and deploy with Maven
-        run: mvn clean deploy -U -Dmaven.test.skip=true
 
-  trigger-dependent-repos:
-    name: Trigger Workflows
-    needs: build
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        dependent-repos: ["bahmni-india-package"]
-    steps:
-      - name: Create repository_dispatch
-        env:
-          REPOSITORY_NAME: ${{ matrix.dependent-repos }}
-        run: |
-          trigger_result=$(curl -s -o trigger_response.txt -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.BAHMNI_PAT }}' https://api.github.com/repos/${ORG_NAME}/${REPOSITORY_NAME}/dispatches -d '{"event_type":"'"${EVENT_TYPE}"'"}')
-          if [ $trigger_result == 204 ];then
-            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Success"
-          else
-            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Failed"
-            cat trigger_response.txt
-            exit 1
-          fi
+  # trigger-dependent-repos:
+  #   name: Trigger Workflows
+  #   needs: build
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     matrix:
+  #       dependent-repos: ["bahmni-india-package"]
+  #   steps:
+  #     - name: Create repository_dispatch
+  #       env:
+  #         REPOSITORY_NAME: ${{ matrix.dependent-repos }}
+  #       run: |
+  #         trigger_result=$(curl -s -o trigger_response.txt -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.BAHMNI_PAT }}' https://api.github.com/repos/${ORG_NAME}/${REPOSITORY_NAME}/dispatches -d '{"event_type":"'"${EVENT_TYPE}"'"}')
+  #         if [ $trigger_result == 204 ];then
+  #           echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Success"
+  #         else
+  #           echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Failed"
+  #           cat trigger_response.txt
+  #           exit 1
+  #         fi
